### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by adamjw3** [yaodingyd/react-flickity-component#132]
Getting an error in storybook, how can i resolve this?
Cannot find module 'flickity'
Error: Cannot find module 'flickity'
    at webpackMissingModule (http://localhost:6006/vendors~main.iframe.bundle.js:126850:86)
    at FlickityComponent.componentDidMount (http://localhost:6006/vendors~main.iframe.bundle.js:126850:169)
    at commitLifeCycles (http://localhost:6006/vendors~main.iframe.bundle.js:120024:24)
    at commitLayoutEffects (http://localhost:6006/vendors~main.iframe.bundle.js:122787:7)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.iframe.bundle.js:103311:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.iframe.bundle.js:103360:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.iframe.bundle.js:103422:31)
    at commitRootImpl (http://localhost:6006/vendors~main.iframe.bundle.js:122512:9)
    at unstable_runWithPriority (http://localhost:6006/vendors~main.iframe.bundle.js:133228:12)
    at runWithPriority$1 (http://localhost:6006/vendors~main.iframe.bundle.js:110642:10)

**Comment by yaodingyd** [comment]
flickity is a peer dependency, you would need to install it seperately
