### ISSUE TITLE
[V4] ReferenceError: window is not defined

### ISSUE THREAD

**Issue by alexw23** [yaodingyd/react-flickity-component#139]
Recently upgraded to the latest version of this package, along side NextJS V13/React V18 etc.

Getting the following error:
```
error - ReferenceError: window is not defined
    at /private/tmp/react-flickity-component-example/node_modules/react-flickity-component/dist/react-flickity-component.umd.js:2:47057
    at /private/tmp/react-flickity-component-example/node_modules/react-flickity-component/dist/react-flickity-component.umd.js:2:47088
    at /private/tmp/react-flickity-component-example/node_modules/react-flickity-component/dist/react-flickity-component.umd.js:1:75
    at Object.<anonymous> (/private/tmp/react-flickity-component-example/node_modules/react-flickity-component/dist/react-flickity-component.umd.js:1:279)
....
```

I found other issues https://github.com/yaodingyd/react-flickity-component/issues/4#issuecomment-486740187 that attempt to solve this issue using the following:

```
const Flickity =
  typeof window !== "undefined"
    ? require("react-flickity-component")
    : () => null
```

However prior to upgrading to V4 we hadn't had this issue.

I've created a clean instance of the react-flickity-component-example, bringing it up to speed with the latest versions and was able to replicate the issue. See the [window-error-demo branch](https://github.com/alexw23/react-flickity-component-example/tree/window-error-demo).

Any idea how we can overcome this issue whilst keeping this component in SSR for performance reasons?

**Comment by yaodingyd** [comment]
Are you sure this branch has your change? the latest commit is still on 11/16/2020.

**Comment by alexw23** [comment]
Code is up now, there was an error pushing which I didn't realise.

**Comment by festevezz** [comment]
same error here

**Comment by yaodingyd** [comment]
can you try v4.0.1?

**Comment by alexw23** [comment]
That's working now, thanks for the fix!
